### ISSUE TITLE
`handleIfs()` replaces parts of variable names if they are "or"

### ISSUE THREAD

**Issue by nitricware** [rgamba/tonic#10]
The ```handleIfs()``` function replaces "or" in a variable name with ```||```.

This makes `$selector` to `$select||` which results in an error because `eval()` fails.

This also happens with the conditions. `{$selector eq "portfolio"}` becomes `{$select|| eq "p||tfolio"}

**Comment by adaniello** [comment]
Stupid idea to fix this issue. At https://github.com/rgamba/tonic/blob/master/src/Tonic.php#L826 replace edit every items of arrays in `str_replace()` adding whitespaces before and after, eg.:

```
$condition=str_replace(array(
   ' eq ',
   ' gt ',
   ...
 ),array(
    ' == ',
   ' > ',
...
),$condition);
```

**Comment by nitricware** [comment]
Actually, I think that's a great solution.
