### ISSUE TITLE
.default modifier breaks variable

### ISSUE THREAD

**Issue by nitricware** [rgamba/tonic#5]
Hy again!

I hand over the variable $file via get and set $_GET as a global just like in your demo. However applying .default to {$context.get.file} just takes the first letter of the original $file and writes that to the document. So if my $file is empty, the default string is also empty. If my $file is itsabeautifulday, the written string will be "i".

I found the reason: if there's a "." In the default value, it breaks the whole thing. My default value was a file like image.gif - removing ".gif" solved the problem.

Yours, Kurt!

**Comment by rgamba** [comment]
Thanks Kurt, I've tracked down the bug, working on it!

**Comment by nitricware** [comment]
Great!
Maybe the other issue I filed is related?

**Comment by rgamba** [comment]
Fixed #4
