### ISSUE TITLE
Bug on loop

### ISSUE THREAD

**Issue by lucaxsilveira** [rgamba/tonic#7]
Hello, i found a Bug in your code

If u have a variable named example: mainmenu, the explode ('in') of handleLoops do not use my variable and explode by in, so : $ma in $menu.
I'm trying to resolve this, but if u know how, tell me haha

**Comment by lucaxsilveira** [comment]
in function **handleLoops**() { 

....
$loop = $this->removeWhiteSpaces($loop);

## **$loop** = str_replace('in$',' in $',$loop);  // just add this line

$loop_det=explode(' in ',$loop);
$loop_name=$loop_det[1];
....

**Comment by rgamba** [comment]
Done, I implemented some fix that solves every scenario in which the "in" word is part of a variable name. Thanks @LucaasSilveira
